language: java

jdk:
 - oraclejdk8

addons:
  sonarcloud:
    organization: "rolan2772-github"
    token:
      secure: "ab0c45e291030aaceb274efbd13262440d7c0335"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'