language: java

jdk:
 - oraclejdk8

addons:
  sonarcloud:
    organization: "rolan2772-github"
    token:
      secure: $SONAR_CLOUD_KEY

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: rolan-currency-converter